# Generated by Django 4.2 on 2024-09-29 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='riot_username',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
