# Generated by Django 4.2 on 2024-10-13 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parties',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(choices=[('0', 'Unranked'), ('1', 'Iron'), ('2', 'Bronze'), ('3', 'Silver'), ('4', 'Gold'), ('5', 'Platinum'), ('6', 'Amarald'), ('7', 'Diamond'), ('8', 'Master'), ('9', 'Grand Master'), ('10', 'Challenger')], max_length=2)),
                ('server', models.CharField(choices=[('KR', 'KR1'), ('LAN', 'LA1'), ('LAS', 'LA2'), ('RU', 'RU1'), ('NA', 'NA1'), ('BR', 'BR1'), ('OCE', 'OC1'), ('EUNE', 'EUN1'), ('EUW', 'EUW1'), ('JP', 'JP1'), ('TR', 'TR1'), ('SG', 'SG2'), ('TH', 'TH2'), ('PH', 'PH2'), ('ME', 'ME1')], max_length=4)),
                ('language', models.CharField(choices=[('KR', '한국어'), ('EN', 'ENGLISH'), ('JP', '日本語')], max_length=2)),
                ('age', models.CharField(choices=[('10', '청소년'), ('20', '청년'), ('30', '중년'), ('40', '중장년')], max_length=2)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_rank', models.BooleanField(default=False)),
                ('adc1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_adc1', to=settings.AUTH_USER_MODEL)),
                ('adc2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_adc2', to=settings.AUTH_USER_MODEL)),
                ('jungle1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_jungle1', to=settings.AUTH_USER_MODEL)),
                ('jungle2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_jungle2', to=settings.AUTH_USER_MODEL)),
                ('mid1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parrty_mid1', to=settings.AUTH_USER_MODEL)),
                ('mid2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_mid2', to=settings.AUTH_USER_MODEL)),
                ('support1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_support1', to=settings.AUTH_USER_MODEL)),
                ('support2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_support2', to=settings.AUTH_USER_MODEL)),
                ('top1', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_top1', to=settings.AUTH_USER_MODEL)),
                ('top2', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='party_top2', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
