# Generated by Django 4.2 on 2024-10-04 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parties', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='parties',
            name='adc1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_adc1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parties',
            name='adc2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_adc2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parties',
            name='jungle1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_jungle1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parties',
            name='jungle2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_jungle2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parties',
            name='mid1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parrty_mid1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parties',
            name='mid2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_mid2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parties',
            name='support1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_support1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parties',
            name='support2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_support2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parties',
            name='top1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_top1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parties',
            name='top2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='party_top2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='parties',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
